apiVersion: apps/v1
kind: Deployment # Метод
metadata: 
  name: my-deployment
  namespace: default  # Namespace в котором будут запускаться поды
spec:
  replicas: 2 # Кол -во Подов
  strategy:  
    type: RollingUpdate # Стратегия обновления поэтапной замены ReplicaSet-1на replicaSet-2/ revisionHistoryLimit история изменения replicaSet
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels: # Селектор поиска своих Подов
      name: my-app # Названия для поиска подов
  template:
    metadata:
      labels:
        name: my-app
    spec: # Спецификация запускаемого Контейнера
      containers:
        - name: nginx
          image: nginx:1.13
          ports:
            - containerPort: 80


# --record=true сохранение истории изменений replicaset
# kubectl rollout undo deployment my-deployment откат изменений
# история изменений по номеру kubectl rollout history deployment my-deployment --revision=2
# история всехизменений kubectl rollout history deployment my-deployment
