---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name: _;
      default_type text/plain;
      location / {
        return200 'Hello from $hostname\n';
      }
    }

---
apiVersion: v1
kind: Deplyment
metadata:
  name: my-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.12
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/